default_context:
    description: Continuous cookiecutter featuring mise
    languages: Node,Python
    peer_checkouts:
        biobuddies/speedrun: main
        biobuddies/wriggle: main
    publish_to_pypi: true
    python_optional_dependencies:
        test:
            - pytest-httpserver
