"""Nominally cover autogenerated files.

AUTOGENERATED by https://github.com/biobuddies/measles
"""
{% if has_django %}
from importlib import import_module


def test_manage_check(monkeypatch):
    monkeypatch.setattr('sys.argv', ['/home/biobuddy/code/speedrun/manage.py', 'check'])
    import_module('manage').main()
{% else %}

def test_boilerplate():
    pass
{% endif -%}
