"""Test boilerplate generation."""
{%- if has_django %}
# AUTOGENERATED by https://github.com/biobuddies/measles
from importlib import import_module


def test_manage_check(monkeypatch):
    monkeypatch.setattr('sys.argv', ['/home/biobuddy/code/newthing/manage.py', 'check'])
    import_module('manage').main()
{% endif %}
